param(
    [string]$ProjectRoot = "C:\xampp\htdocs\HomeRes",
    [string]$ApacheRoot = "C:\xampp\apache"
)

$ErrorActionPreference = 'Stop'

function Find-Mkcert {
    $candidates = @(
        (Join-Path $env:LOCALAPPDATA 'Microsoft\WinGet\Packages\FiloSottile.mkcert_Microsoft.Winget.Source_8wekyb3d8bbwe\mkcert.exe'),
        (Get-Command mkcert -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source -ErrorAction SilentlyContinue)
    ) | Where-Object { $_ -and (Test-Path $_) }

    return $candidates | Select-Object -First 1
}

$mkcert = Find-Mkcert
if (-not $mkcert) {
    throw 'mkcert no esta instalado. Instala mkcert primero y vuelve a ejecutar este script.'
}

$publicPath = Join-Path $ProjectRoot 'public'
if (-not (Test-Path $publicPath)) {
    throw "No se encontro el directorio public del proyecto en $publicPath"
}

$certDir = Join-Path $ProjectRoot 'storage\certs'
New-Item -ItemType Directory -Force -Path $certDir | Out-Null

$certFile = Join-Path $certDir 'localhost.pem'
$keyFile = Join-Path $certDir 'localhost-key.pem'

& $mkcert -install | Out-Host
Push-Location $certDir
& $mkcert -cert-file $certFile -key-file $keyFile localhost 127.0.0.1 ::1 | Out-Host
Pop-Location

$sslConfPath = Join-Path $ApacheRoot 'conf\extra\httpd-ssl.conf'
if (-not (Test-Path $sslConfPath)) {
    throw "No se encontro httpd-ssl.conf en $sslConfPath"
}

$backupPath = "$sslConfPath.bak"
Copy-Item $sslConfPath $backupPath -Force

$sslConf = @"
# HomeRes local HTTPS configuration generated by scripts/setup-local-https.ps1
Listen 443

SSLSessionCache "shmcb:C:/xampp/apache/logs/ssl_scache(512000)"
SSLSessionCacheTimeout 300

<VirtualHost _default_:443>
    DocumentRoot "$($publicPath -replace '\\','/')"
    ServerName localhost:443
    ServerAdmin admin@localhost

    ErrorLog "C:/xampp/apache/logs/homeres-ssl-error.log"
    TransferLog "C:/xampp/apache/logs/homeres-ssl-access.log"

    SSLEngine on
    SSLCertificateFile "$($certFile -replace '\\','/')"
    SSLCertificateKeyFile "$($keyFile -replace '\\','/')"

    <Directory "$($publicPath -replace '\\','/')">
        AllowOverride All
        Require all granted
        Options Indexes FollowSymLinks Includes ExecCGI
    </Directory>

    BrowserMatch "MSIE [2-6]" \
        nokeepalive ssl-unclean-shutdown \
        downgrade-1.0 force-response-1.0

    CustomLog "C:/xampp/apache/logs/ssl_request.log" \
        "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"
</VirtualHost>
"@

Set-Content -Path $sslConfPath -Value $sslConf -Encoding ASCII

Write-Host ''
Write-Host 'HTTPS local configurado para HomeRes.'
Write-Host "Certificado: $certFile"
Write-Host "Clave: $keyFile"
Write-Host "Backup SSL conf: $backupPath"
Write-Host 'Reinicia Apache y abre https://localhost/'